/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsVigoraRouteImport } from './routes/products.vigora'
import { Route as ProductsSuperPotassiumShinyFlakes98RouteImport } from './routes/products.super-potassium-shiny-flakes-98'
import { Route as ProductsSuperFHumateBigShinyFlakesRouteImport } from './routes/products.super-f-humate-big-shiny-flakes'
import { Route as ProductsGlycineRouteImport } from './routes/products.glycine'
import { Route as OrderSlugRouteImport } from './routes/order.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known.agent-skills.index[.]json'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVigoraRoute = ProductsVigoraRouteImport.update({
  id: '/products/vigora',
  path: '/products/vigora',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSuperPotassiumShinyFlakes98Route =
  ProductsSuperPotassiumShinyFlakes98RouteImport.update({
    id: '/products/super-potassium-shiny-flakes-98',
    path: '/products/super-potassium-shiny-flakes-98',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsSuperFHumateBigShinyFlakesRoute =
  ProductsSuperFHumateBigShinyFlakesRouteImport.update({
    id: '/products/super-f-humate-big-shiny-flakes',
    path: '/products/super-f-humate-big-shiny-flakes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsGlycineRoute = ProductsGlycineRouteImport.update({
  id: '/products/glycine',
  path: '/products/glycine',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSlugRoute = OrderSlugRouteImport.update({
  id: '/order/$slug',
  path: '/order/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/order/$slug': typeof OrderSlugRoute
  '/products/glycine': typeof ProductsGlycineRoute
  '/products/super-f-humate-big-shiny-flakes': typeof ProductsSuperFHumateBigShinyFlakesRoute
  '/products/super-potassium-shiny-flakes-98': typeof ProductsSuperPotassiumShinyFlakes98Route
  '/products/vigora': typeof ProductsVigoraRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/order/$slug': typeof OrderSlugRoute
  '/products/glycine': typeof ProductsGlycineRoute
  '/products/super-f-humate-big-shiny-flakes': typeof ProductsSuperFHumateBigShinyFlakesRoute
  '/products/super-potassium-shiny-flakes-98': typeof ProductsSuperPotassiumShinyFlakes98Route
  '/products/vigora': typeof ProductsVigoraRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/order/$slug': typeof OrderSlugRoute
  '/products/glycine': typeof ProductsGlycineRoute
  '/products/super-f-humate-big-shiny-flakes': typeof ProductsSuperFHumateBigShinyFlakesRoute
  '/products/super-potassium-shiny-flakes-98': typeof ProductsSuperPotassiumShinyFlakes98Route
  '/products/vigora': typeof ProductsVigoraRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/admin'
    | '/order/$slug'
    | '/products/glycine'
    | '/products/super-f-humate-big-shiny-flakes'
    | '/products/super-potassium-shiny-flakes-98'
    | '/products/vigora'
    | '/.well-known/agent-skills/index.json'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/admin'
    | '/order/$slug'
    | '/products/glycine'
    | '/products/super-f-humate-big-shiny-flakes'
    | '/products/super-potassium-shiny-flakes-98'
    | '/products/vigora'
    | '/.well-known/agent-skills/index.json'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/applications'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/.well-known/api-catalog'
    | '/_authenticated/admin'
    | '/order/$slug'
    | '/products/glycine'
    | '/products/super-f-humate-big-shiny-flakes'
    | '/products/super-potassium-shiny-flakes-98'
    | '/products/vigora'
    | '/.well-known/agent-skills/index.json'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  OrderSlugRoute: typeof OrderSlugRoute
  ProductsGlycineRoute: typeof ProductsGlycineRoute
  ProductsSuperFHumateBigShinyFlakesRoute: typeof ProductsSuperFHumateBigShinyFlakesRoute
  ProductsSuperPotassiumShinyFlakes98Route: typeof ProductsSuperPotassiumShinyFlakes98Route
  ProductsVigoraRoute: typeof ProductsVigoraRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/vigora': {
      id: '/products/vigora'
      path: '/products/vigora'
      fullPath: '/products/vigora'
      preLoaderRoute: typeof ProductsVigoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/super-potassium-shiny-flakes-98': {
      id: '/products/super-potassium-shiny-flakes-98'
      path: '/products/super-potassium-shiny-flakes-98'
      fullPath: '/products/super-potassium-shiny-flakes-98'
      preLoaderRoute: typeof ProductsSuperPotassiumShinyFlakes98RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/super-f-humate-big-shiny-flakes': {
      id: '/products/super-f-humate-big-shiny-flakes'
      path: '/products/super-f-humate-big-shiny-flakes'
      fullPath: '/products/super-f-humate-big-shiny-flakes'
      preLoaderRoute: typeof ProductsSuperFHumateBigShinyFlakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/glycine': {
      id: '/products/glycine'
      path: '/products/glycine'
      fullPath: '/products/glycine'
      preLoaderRoute: typeof ProductsGlycineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$slug': {
      id: '/order/$slug'
      path: '/order/$slug'
      fullPath: '/order/$slug'
      preLoaderRoute: typeof OrderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  OrderSlugRoute: OrderSlugRoute,
  ProductsGlycineRoute: ProductsGlycineRoute,
  ProductsSuperFHumateBigShinyFlakesRoute:
    ProductsSuperFHumateBigShinyFlakesRoute,
  ProductsSuperPotassiumShinyFlakes98Route:
    ProductsSuperPotassiumShinyFlakes98Route,
  ProductsVigoraRoute: ProductsVigoraRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
